export const Items = [
  {
    id: 1,
    category: "Brackfast",
    title: "Brackfast",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Brackfast.jpeg"),
    price: 38,
  },
  {
    id: 2,
    category: "Lunch",
    title: "Lunch",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Lunch.jpeg"),
    price: 119,
  },
  {
    id: 3,
    category: "Dinner",
    title: "Dinner",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Dinner.png"),
    price: 65,
  },
  {
    id: 4,
    category: "Snacks",
    title: "Snacks",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Snacks.jpeg"),
    price: 17,
  },
  {
    id: 1,
    category: "Brackfast",
    title: "Brackfast",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Brackfast.jpeg"),
    price: 38,
  },
  {
    id: 2,
    category: "Lunch",
    title: "Lunch",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Lunch.jpeg"),
    price: 119,
  },
  {
    id: 3,
    category: "Dinner",
    title: "Dinner",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Dinner.png"),
    price: 65,
  },
  {
    id: 4,
    category: "Snacks",
    title: "Snacks",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Snacks.jpeg"),
    price: 17,
  },
  {
    id: 1,
    category: "Brackfast",
    title: "Brackfast",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Brackfast.jpeg"),
    price: 38,
  },
  {
    id: 2,
    category: "Lunch",
    title: "Lunch",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Lunch.jpeg"),
    price: 119,
  },
  {
    id: 5,
    category: "Dessert",
    title: "Dessert",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Dessert.jpeg"),
    price: 17,
  },
  {
    id: 3,
    category: "Dinner",
    title: "Dinner",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Dinner.png"),
    price: 65,
  },
  {
    id: 4,
    category: "Snacks",
    title: "Snacks",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Snacks.jpeg"),
    price: 17,
  },
  {
    id: 5,
    category: "Dessert",
    title: "Dessert",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Dessert.jpeg"),
    price: 17,
  },
  {
    id: 1,
    category: "Brackfast",
    title: "Brackfast",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Brackfast.jpeg"),
    price: 38,
  },
  {
    id: 2,
    category: "Lunch",
    title: "Lunch",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Lunch.jpeg"),
    price: 119,
  },
  {
    id: 5,
    category: "Dessert",
    title: "Dessert",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Dessert.jpeg"),
    price: 17,
  },
  {
    id: 3,
    category: "Dinner",
    title: "Dinner",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Dinner.png"),
    price: 65,
  },
  {
    id: 4,
    category: "Snacks",
    title: "Snacks",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Snacks.jpeg"),
    price: 17,
  },
  {
    id: 5,
    category: "Dessert",
    title: "Dessert",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Dessert.jpeg"),
    price: 17,
  },
  {
    id: 1,
    category: "Brackfast",
    title: "Brackfast",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Brackfast.jpeg"),
    price: 38,
  },
  {
    id: 2,
    category: "Lunch",
    title: "Lunch",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Lunch.jpeg"),
    price: 119,
  },
  {
    id: 3,
    category: "Dinner",
    title: "Dinner",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Dinner.png"),
    price: 65,
  },
  {
    id: 5,
    category: "Dessert",
    title: "Dessert",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Dessert.jpeg"),
    price: 17,
  },
  {
    id: 4,
    category: "Snacks",
    title: "Snacks",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Snacks.jpeg"),
    price: 17,
  },
  {
    id: 1,
    category: "Brackfast",
    title: "Brackfast",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Brackfast.jpeg"),
    price: 38,
  },
  {
    id: 5,
    category: "Dessert",
    title: "Dessert",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Dessert.jpeg"),
    price: 17,
  },
  {
    id: 2,
    category: "Lunch",
    title: "Lunch",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Lunch.jpeg"),
    price: 119,
  },
  {
    id: 3,
    category: "Dinner",
    title: "Dinner",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Dinner.png"),
    price: 65,
  },
  {
    id: 5,
    category: "Dessert",
    title: "Dessert",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Dessert.jpeg"),
    price: 17,
  },
  {
    id: 4,
    category: "Snacks",
    title: "Snacks",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Snacks.jpeg"),
    price: 17,
  },
  {
    id: 5,
    category: "Dessert",
    title: "Dessert",
    desc: "This is a longer card with supporting text below as a natural lead-in to additional content.",
    img: require("./Images/Dessert.jpeg"),
    price: 17,
  },
];
